version: '3'

services:
  postgres:
    container_name: postgres_microservices
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Komissar1918
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_planner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq_microservices
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:



#после запуска контейнера нужно 2 раза ввести команду в терминале контейнера postgres: createdb -U Komissar1918 <название бд>
